### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by tyler36** [breeze2/vscode-phpstan#4]
I'm having problems using this extension. At first,it didn't seem to do anything.  I checked the logs and found the following error

```
[2019-02-15 12:52:22.726] [renderer1] [error] Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>:null:null)
    at ChildProcess.analyse.phpstan.on.code (C:\Users\XXXXXXX\.vscode\extensions\breezelin.phpstan-1.0.6\out\controller.js:184:29)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

I can successfully run the following command from the project root, so I assume PHPstan is functioning:
```
phpstan analyse app --level 3
```

OS: Win10
PHP Static Analysis: 1.0.6
VS: 1.31.1

**Comment by breeze2** [comment]
Since phpstan `0.11`, the command option `--errorFormat`, has been renamed to `--error-format`.
Please update the vscode extension PHP Static Analysis to `v1.1.0`.
Thanks for your feedback!

**Comment by tyler36** [comment]
Extension auto-updated as I was reading your reply. After a reload, it works! 

Thank you for making the changes. And thank you for making the extension.
